=begin
#Network Storage API

#Create, list, edit, and delete storage networks with the Network Storage API. Use storage networks to expand storage capacity on a private network. <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/bare-metal-cloud-storage' target='_blank'>here</a> </span> <br> <b>All URLs are relative to (https://api.phoenixnap.com/network-storage/v1/)</b> 

The version of the OpenAPI document: 1.0
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'pnap_network_storage_api/api_client'
require 'pnap_network_storage_api/api_error'
require 'pnap_network_storage_api/version'
require 'pnap_network_storage_api/configuration'

# Models
require 'pnap_network_storage_api/models/error'
require 'pnap_network_storage_api/models/nfs_permissions'
require 'pnap_network_storage_api/models/permissions'
require 'pnap_network_storage_api/models/status'
require 'pnap_network_storage_api/models/storage_network'
require 'pnap_network_storage_api/models/storage_network_create'
require 'pnap_network_storage_api/models/storage_network_update'
require 'pnap_network_storage_api/models/volume'
require 'pnap_network_storage_api/models/volume_create'
require 'pnap_network_storage_api/models/volume_update'

# APIs
require 'pnap_network_storage_api/api/storage_networks_api'

module NetworkStorageApi
  class << self
    # Customize default settings for the SDK using block.
    #   NetworkStorageApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
