=begin
#Audit Log API

#The Audit Logs API lets you read audit log entries and track API calls or activities in the Bare Metal Cloud Portal.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/bmc-server-management-via-api#audit-log-api' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/audit/v1/)</b> 

The version of the OpenAPI document: 1.0
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'pnap_audit_api/api_client'
require 'pnap_audit_api/api_error'
require 'pnap_audit_api/version'
require 'pnap_audit_api/configuration'

# Models
require 'pnap_audit_api/models/api_action'
require 'pnap_audit_api/models/api_action_all_of'
require 'pnap_audit_api/models/event'
require 'pnap_audit_api/models/headers'
require 'pnap_audit_api/models/request'
require 'pnap_audit_api/models/response'
require 'pnap_audit_api/models/user_info'

# APIs
require 'pnap_audit_api/api/events_api'

module AuditApi
  class << self
    # Customize default settings for the SDK using block.
    #   AuditApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
