source "https://rubygems.org"

gem 'pnap_audit_api', path: '../AuditApi'
gem 'pnap_bmc_api', path: '../BmcApi'
gem 'pnap_ip_api', path: '../IpApi'
gem 'pnap_network_api', path: '../NetworkApi'
gem 'pnap_rancher_api', path: '../RancherApi'
gem 'pnap_tag_api', path: '../TagApi'
gem 'pnap_network_storage_api', path: '../NetworkStorageApi'
gem 'pnap_location_api', path: '../LocationApi'
gem 'pnap_billing_api', path: '../BillingApi'
gem 'pnap_payments_api', path: '../PaymentsApi'

gem 'oauth2', "1.4.9"
gem 'test-unit', "3.5.3"
gem 'json', "2.6.1"
gem 'test-unit-runner-junitxml', "1.0.0"
gem "typhoeus", "~> 1.4"
