=begin
#Locations API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LocationApi::ProductLocationEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LocationApi::ProductLocationEnum do
  let(:instance) { LocationApi::ProductLocationEnum.new }

  describe 'test an instance of ProductLocationEnum' do
    it 'should create an instance of ProductLocationEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LocationApi::ProductLocationEnum)
    end
  end

end
