=begin
#Payments API

#Payments API are currently designed to fetch Transactions only.

The version of the OpenAPI document: 0.1
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PaymentsApi::CardPaymentMethodDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PaymentsApi::CardPaymentMethodDetails do
  let(:instance) { PaymentsApi::CardPaymentMethodDetails.new }

  describe 'test an instance of CardPaymentMethodDetails' do
    it 'should create an instance of CardPaymentMethodDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PaymentsApi::CardPaymentMethodDetails)
    end
  end

  describe 'test attribute "card_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "last_four_digits"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
