=begin
#Rancher Solution API

#Simplify enterprise-grade Kubernetes cluster operations and management with Rancher on Bare Metal Cloud. Deploy Kubernetes clusters using a few API calls.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/rancher-bmc-integration-kubernetes' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/solutions/rancher/v1beta)</b> 

The version of the OpenAPI document: 0.1
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'pnap_rancher_api/api_client'
require 'pnap_rancher_api/api_error'
require 'pnap_rancher_api/version'
require 'pnap_rancher_api/configuration'

# Models
require 'pnap_rancher_api/models/cluster'
require 'pnap_rancher_api/models/delete_result'
require 'pnap_rancher_api/models/error'
require 'pnap_rancher_api/models/node'
require 'pnap_rancher_api/models/node_pool'
require 'pnap_rancher_api/models/rancher_cluster_certificates'
require 'pnap_rancher_api/models/rancher_cluster_config'
require 'pnap_rancher_api/models/rancher_server_metadata'
require 'pnap_rancher_api/models/ssh_config'
require 'pnap_rancher_api/models/workload_cluster_config'

# APIs
require 'pnap_rancher_api/api/clusters_api'

module RancherApi
  class << self
    # Customize default settings for the SDK using block.
    #   RancherApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
