=begin
#Billing API

#Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a given period and enable or disable auto-renewals.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b> 

The version of the OpenAPI document: 0.1
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module BillingApi
  # Details of the bandwidth associated with this rated usage record.
  class BandwidthDetails < ApiModelBase
    # The amount of GB consumed in ingress (IN).
    attr_accessor :ingress_gb

    # The amount of GB consumed in egress (OUT).
    attr_accessor :egress_gb

    # Package size per month.
    attr_accessor :package_quantity

    # Package size unit.
    attr_accessor :package_unit

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ingress_gb' => :'ingressGb',
        :'egress_gb' => :'egressGb',
        :'package_quantity' => :'packageQuantity',
        :'package_unit' => :'packageUnit'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ingress_gb' => :'Float',
        :'egress_gb' => :'Float',
        :'package_quantity' => :'Float',
        :'package_unit' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BillingApi::BandwidthDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BillingApi::BandwidthDetails`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ingress_gb')
        self.ingress_gb = attributes[:'ingress_gb']
      else
        self.ingress_gb = nil
      end

      if attributes.key?(:'egress_gb')
        self.egress_gb = attributes[:'egress_gb']
      else
        self.egress_gb = nil
      end

      if attributes.key?(:'package_quantity')
        self.package_quantity = attributes[:'package_quantity']
      end

      if attributes.key?(:'package_unit')
        self.package_unit = attributes[:'package_unit']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @ingress_gb.nil?
        invalid_properties.push('invalid value for "ingress_gb", ingress_gb cannot be nil.')
      end

      if @egress_gb.nil?
        invalid_properties.push('invalid value for "egress_gb", egress_gb cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @ingress_gb.nil?
      return false if @egress_gb.nil?
      package_unit_validator = EnumAttributeValidator.new('String', ["GB", "TB"])
      return false unless package_unit_validator.valid?(@package_unit)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] ingress_gb Value to be assigned
    def ingress_gb=(ingress_gb)
      if ingress_gb.nil?
        fail ArgumentError, 'ingress_gb cannot be nil'
      end

      @ingress_gb = ingress_gb
    end

    # Custom attribute writer method with validation
    # @param [Object] egress_gb Value to be assigned
    def egress_gb=(egress_gb)
      if egress_gb.nil?
        fail ArgumentError, 'egress_gb cannot be nil'
      end

      @egress_gb = egress_gb
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] package_unit Object to be assigned
    def package_unit=(package_unit)
      validator = EnumAttributeValidator.new('String', ["GB", "TB"])
      unless validator.valid?(package_unit)
        fail ArgumentError, "invalid value for \"package_unit\", must be one of #{validator.allowable_values}."
      end
      @package_unit = package_unit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ingress_gb == o.ingress_gb &&
          egress_gb == o.egress_gb &&
          package_quantity == o.package_quantity &&
          package_unit == o.package_unit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ingress_gb, egress_gb, package_quantity, package_unit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
