=begin
#Billing API

#Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a given period and enable or disable auto-renewals.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b> 

The version of the OpenAPI document: 0.1
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module BillingApi
  # Info about location, solutions and availability for a product.
  class LocationAvailabilityDetail < ApiModelBase
    attr_accessor :location

    # Requested quantity.
    attr_accessor :min_quantity_requested

    # Is product available in specific location for requested quantity
    attr_accessor :min_quantity_available

    # Total available quantity of product in specific location. Max value is 10.
    attr_accessor :available_quantity

    # Solutions supported in specific location for a product.
    attr_accessor :solutions

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'location' => :'location',
        :'min_quantity_requested' => :'minQuantityRequested',
        :'min_quantity_available' => :'minQuantityAvailable',
        :'available_quantity' => :'availableQuantity',
        :'solutions' => :'solutions'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'location' => :'ProductLocationEnum',
        :'min_quantity_requested' => :'Float',
        :'min_quantity_available' => :'Boolean',
        :'available_quantity' => :'Float',
        :'solutions' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BillingApi::LocationAvailabilityDetail` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BillingApi::LocationAvailabilityDetail`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      else
        self.location = nil
      end

      if attributes.key?(:'min_quantity_requested')
        self.min_quantity_requested = attributes[:'min_quantity_requested']
      else
        self.min_quantity_requested = nil
      end

      if attributes.key?(:'min_quantity_available')
        self.min_quantity_available = attributes[:'min_quantity_available']
      else
        self.min_quantity_available = nil
      end

      if attributes.key?(:'available_quantity')
        self.available_quantity = attributes[:'available_quantity']
      else
        self.available_quantity = nil
      end

      if attributes.key?(:'solutions')
        if (value = attributes[:'solutions']).is_a?(Array)
          self.solutions = value
        end
      else
        self.solutions = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @location.nil?
        invalid_properties.push('invalid value for "location", location cannot be nil.')
      end

      if @min_quantity_requested.nil?
        invalid_properties.push('invalid value for "min_quantity_requested", min_quantity_requested cannot be nil.')
      end

      if @min_quantity_available.nil?
        invalid_properties.push('invalid value for "min_quantity_available", min_quantity_available cannot be nil.')
      end

      if @available_quantity.nil?
        invalid_properties.push('invalid value for "available_quantity", available_quantity cannot be nil.')
      end

      if @solutions.nil?
        invalid_properties.push('invalid value for "solutions", solutions cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @location.nil?
      return false if @min_quantity_requested.nil?
      return false if @min_quantity_available.nil?
      return false if @available_quantity.nil?
      return false if @solutions.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] location Value to be assigned
    def location=(location)
      if location.nil?
        fail ArgumentError, 'location cannot be nil'
      end

      @location = location
    end

    # Custom attribute writer method with validation
    # @param [Object] min_quantity_requested Value to be assigned
    def min_quantity_requested=(min_quantity_requested)
      if min_quantity_requested.nil?
        fail ArgumentError, 'min_quantity_requested cannot be nil'
      end

      @min_quantity_requested = min_quantity_requested
    end

    # Custom attribute writer method with validation
    # @param [Object] min_quantity_available Value to be assigned
    def min_quantity_available=(min_quantity_available)
      if min_quantity_available.nil?
        fail ArgumentError, 'min_quantity_available cannot be nil'
      end

      @min_quantity_available = min_quantity_available
    end

    # Custom attribute writer method with validation
    # @param [Object] available_quantity Value to be assigned
    def available_quantity=(available_quantity)
      if available_quantity.nil?
        fail ArgumentError, 'available_quantity cannot be nil'
      end

      @available_quantity = available_quantity
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          location == o.location &&
          min_quantity_requested == o.min_quantity_requested &&
          min_quantity_available == o.min_quantity_available &&
          available_quantity == o.available_quantity &&
          solutions == o.solutions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [location, min_quantity_requested, min_quantity_available, available_quantity, solutions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
