=begin
#Billing API

#Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a given period and enable or disable auto-renewals.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b> 

The version of the OpenAPI document: 0.1
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module BillingApi
  # Details of the storage associated with this rated usage record.
  class StorageDetails < ApiModelBase
    # Network storage ID.
    attr_accessor :network_storage_id

    # Network storage name.
    attr_accessor :network_storage_name

    # Volume ID.
    attr_accessor :volume_id

    # Volume name.
    attr_accessor :volume_name

    # Capacity in GB.
    attr_accessor :capacity_in_gb

    # Timestamp when the record was created.
    attr_accessor :created_on

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'network_storage_id' => :'networkStorageId',
        :'network_storage_name' => :'networkStorageName',
        :'volume_id' => :'volumeId',
        :'volume_name' => :'volumeName',
        :'capacity_in_gb' => :'capacityInGb',
        :'created_on' => :'createdOn'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'network_storage_id' => :'String',
        :'network_storage_name' => :'String',
        :'volume_id' => :'String',
        :'volume_name' => :'String',
        :'capacity_in_gb' => :'Integer',
        :'created_on' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BillingApi::StorageDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BillingApi::StorageDetails`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'network_storage_id')
        self.network_storage_id = attributes[:'network_storage_id']
      end

      if attributes.key?(:'network_storage_name')
        self.network_storage_name = attributes[:'network_storage_name']
      end

      if attributes.key?(:'volume_id')
        self.volume_id = attributes[:'volume_id']
      end

      if attributes.key?(:'volume_name')
        self.volume_name = attributes[:'volume_name']
      end

      if attributes.key?(:'capacity_in_gb')
        self.capacity_in_gb = attributes[:'capacity_in_gb']
      else
        self.capacity_in_gb = nil
      end

      if attributes.key?(:'created_on')
        self.created_on = attributes[:'created_on']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @capacity_in_gb.nil?
        invalid_properties.push('invalid value for "capacity_in_gb", capacity_in_gb cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @capacity_in_gb.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] capacity_in_gb Value to be assigned
    def capacity_in_gb=(capacity_in_gb)
      if capacity_in_gb.nil?
        fail ArgumentError, 'capacity_in_gb cannot be nil'
      end

      @capacity_in_gb = capacity_in_gb
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          network_storage_id == o.network_storage_id &&
          network_storage_name == o.network_storage_name &&
          volume_id == o.volume_id &&
          volume_name == o.volume_name &&
          capacity_in_gb == o.capacity_in_gb &&
          created_on == o.created_on
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [network_storage_id, network_storage_name, volume_id, volume_name, capacity_in_gb, created_on].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
