=begin
#Bare Metal Cloud API

#Create, power off, power on, reset, reboot, or shut down your server with the Bare Metal Cloud API.  Deprovision servers, get or edit SSH key details, assign public IPs, assign servers to networks and a lot more.  Manage your infrastructure more efficiently using just a few simple API calls.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/how-to-deploy-bare-metal-cloud-server' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/bmc/v1/)</b> 

The version of the OpenAPI document: 0.1
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module BmcApi
  # Netris Softgate configuration properties. Follow <a href='https://phoenixnap.com/kb/netris-bare-metal-cloud#deploy-netris-softgate' target='_blank'>instructions</a> for retrieving the required details.
  class OsConfigurationNetrisSoftgate < ApiModelBase
    # (Read-only) Host OS on which the Netris Softgate is installed.
    attr_accessor :host_os

    # (Write-only) IP address or hostname through which to reach the Netris Controller.
    attr_accessor :controller_address

    # (Write-only) The version of the Netris Controller to connect to.
    attr_accessor :controller_version

    # (Write-only) The authentication key of the Netris Controller to connect to. Required for the softgate agent to be able to interact with the Netris Controller.
    attr_accessor :controller_auth_key

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'host_os' => :'hostOs',
        :'controller_address' => :'controllerAddress',
        :'controller_version' => :'controllerVersion',
        :'controller_auth_key' => :'controllerAuthKey'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'host_os' => :'String',
        :'controller_address' => :'String',
        :'controller_version' => :'String',
        :'controller_auth_key' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BmcApi::OsConfigurationNetrisSoftgate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BmcApi::OsConfigurationNetrisSoftgate`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'host_os')
        self.host_os = attributes[:'host_os']
      end

      if attributes.key?(:'controller_address')
        self.controller_address = attributes[:'controller_address']
      end

      if attributes.key?(:'controller_version')
        self.controller_version = attributes[:'controller_version']
      end

      if attributes.key?(:'controller_auth_key')
        self.controller_auth_key = attributes[:'controller_auth_key']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@controller_address.nil? && @controller_address.to_s.length > 253
        invalid_properties.push('invalid value for "controller_address", the character length must be smaller than or equal to 253.')
      end

      pattern = Regexp.new(/^(?!-)[\w\-]{1,63}(?<!-)(\.(?!-)[\w\-]{1,63}(?<!-))*$/)
      if !@controller_address.nil? && @controller_address !~ pattern
        invalid_properties.push("invalid value for \"controller_address\", must conform to the pattern #{pattern}.")
      end

      if !@controller_version.nil? && @controller_version.to_s.length > 20
        invalid_properties.push('invalid value for "controller_version", the character length must be smaller than or equal to 20.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9.-]+$/)
      if !@controller_version.nil? && @controller_version !~ pattern
        invalid_properties.push("invalid value for \"controller_version\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^\S+$/)
      if !@controller_auth_key.nil? && @controller_auth_key !~ pattern
        invalid_properties.push("invalid value for \"controller_auth_key\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@controller_address.nil? && @controller_address.to_s.length > 253
      return false if !@controller_address.nil? && @controller_address !~ Regexp.new(/^(?!-)[\w\-]{1,63}(?<!-)(\.(?!-)[\w\-]{1,63}(?<!-))*$/)
      return false if !@controller_version.nil? && @controller_version.to_s.length > 20
      return false if !@controller_version.nil? && @controller_version !~ Regexp.new(/^[a-zA-Z0-9.-]+$/)
      return false if !@controller_auth_key.nil? && @controller_auth_key !~ Regexp.new(/^\S+$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_address Value to be assigned
    def controller_address=(controller_address)
      if controller_address.nil?
        fail ArgumentError, 'controller_address cannot be nil'
      end

      if controller_address.to_s.length > 253
        fail ArgumentError, 'invalid value for "controller_address", the character length must be smaller than or equal to 253.'
      end

      pattern = Regexp.new(/^(?!-)[\w\-]{1,63}(?<!-)(\.(?!-)[\w\-]{1,63}(?<!-))*$/)
      if controller_address !~ pattern
        fail ArgumentError, "invalid value for \"controller_address\", must conform to the pattern #{pattern}."
      end

      @controller_address = controller_address
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_version Value to be assigned
    def controller_version=(controller_version)
      if controller_version.nil?
        fail ArgumentError, 'controller_version cannot be nil'
      end

      if controller_version.to_s.length > 20
        fail ArgumentError, 'invalid value for "controller_version", the character length must be smaller than or equal to 20.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9.-]+$/)
      if controller_version !~ pattern
        fail ArgumentError, "invalid value for \"controller_version\", must conform to the pattern #{pattern}."
      end

      @controller_version = controller_version
    end

    # Custom attribute writer method with validation
    # @param [Object] controller_auth_key Value to be assigned
    def controller_auth_key=(controller_auth_key)
      if controller_auth_key.nil?
        fail ArgumentError, 'controller_auth_key cannot be nil'
      end

      pattern = Regexp.new(/^\S+$/)
      if controller_auth_key !~ pattern
        fail ArgumentError, "invalid value for \"controller_auth_key\", must conform to the pattern #{pattern}."
      end

      @controller_auth_key = controller_auth_key
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          host_os == o.host_os &&
          controller_address == o.controller_address &&
          controller_version == o.controller_version &&
          controller_auth_key == o.controller_auth_key
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [host_os, controller_address, controller_version, controller_auth_key].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
