name: 'Test SDK'
description: 'Test SDK using a given test file.'
inputs:
  test-file: 
    description: 'Name of the test file to run.'
    required: true
  test-report-dir:
    description: 'Location of the test reports.'
    required: true
  ruby-version: 
    description: 'Version of Ruby to run tests on.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
    - name: Setup Ruby
      uses: ./.github/workflows/composite/setup-ruby
      with:
        ruby-version: ${{ inputs.ruby-version }}
    - name: Install Bundler
      shell: bash
      run: |
        if [[ ${{ inputs.ruby-version }} -lt 3 ]]
        then
          gem install bundler -v 2.4.22
        else
          gem install bundler
        fi
    - name: Run tests
      shell: bash
      run: |
        cd tests
        bundler install
        bundler exec ruby ${{ inputs.test-file }} --runner=junitxml --junitxml-output-file=result.xml
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '${{ inputs.test-report-dir }}/*'