name: 'Test SDK'
description: 'Test SDK using a given test file.'
inputs:
  test-file: 
    description: 'Name of the test file to run.'
    required: true
  test-report-dir:
    description: 'Location of the test reports.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
    - uses: ./.github/workflows/composite/setup-ruby
    - name: Install Bundler
      shell: bash
      run: gem install bundler
    - name: Run tests
      shell: bash
      run: |
        cd tests
        bundler install
        bundler exec ruby ${{ inputs.test-file }} --runner=junitxml --junitxml-output-file=result.xml
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '${{ inputs.test-report-dir }}/*'