name: 'Setup Ruby'
description: 'Sets up Ruby and generic configuration'
runs:
  using: "composite"
  steps:
    - name: Setup Ruby with Version
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1