=begin
#Billing API

#Automate your infrastructure billing with the Bare Metal Cloud Billing API. Reserve your server instances to ensure guaranteed resource availability for 12, 24, and 36 months. Retrieve your server’s rated usage for a given period and enable or disable auto-renewals.<br> <br> <span class='pnap-api-knowledge-base-link'> Knowledge base articles to help you can be found <a href='https://phoenixnap.com/kb/phoenixnap-bare-metal-cloud-billing-models' target='_blank'>here</a> </span><br> <br> <b>All URLs are relative to (https://api.phoenixnap.com/billing/v1/)</b> 

The version of the OpenAPI document: 0.1
Contact: support@phoenixnap.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BillingApi::ReservationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReservationsApi' do
  before do
    # run before each test
    @api_instance = BillingApi::ReservationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReservationsApi' do
    it 'should create an instance of ReservationsApi' do
      expect(@api_instance).to be_instance_of(BillingApi::ReservationsApi)
    end
  end

  # unit tests for reservations_get
  # List all Reservations.
  # Retrieves all reservations associated with the authenticated account. All date &amp; times are in UTC.
  # @param [Hash] opts the optional parameters
  # @option opts [ReservationProductCategoryEnum] :product_category The product category
  # @return [Array<Reservation>]
  describe 'reservations_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reservations_post
  # Create a reservation.
  # Creates new package reservation for authenticated account.
  # @param [Hash] opts the optional parameters
  # @option opts [ReservationRequest] :reservation_request 
  # @return [Reservation]
  describe 'reservations_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reservations_reservation_id_actions_auto_renew_disable_post
  # Disable auto-renewal for reservation by id.
  # Disable auto-renewal for reservation by reservation id.
  # @param id Resource id.
  # @param [Hash] opts the optional parameters
  # @option opts [ReservationAutoRenewDisableRequest] :reservation_auto_renew_disable_request 
  # @return [Reservation]
  describe 'reservations_reservation_id_actions_auto_renew_disable_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reservations_reservation_id_actions_auto_renew_enable_post
  # Enable auto-renewal for unexpired reservation by reservation id.
  # Enable auto-renewal for unexpired reservation by reservation id.
  # @param id Resource id.
  # @param [Hash] opts the optional parameters
  # @return [Reservation]
  describe 'reservations_reservation_id_actions_auto_renew_enable_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reservations_reservation_id_actions_convert_post
  # Convert reservation pricing model by reservation ID.
  # Convert reservation pricing model by reservation id.
  # @param id Resource id.
  # @param [Hash] opts the optional parameters
  # @option opts [ReservationRequest] :reservation_request 
  # @return [Reservation]
  describe 'reservations_reservation_id_actions_convert_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reservations_reservation_id_get
  # Get a reservation.
  # Retrieves the reservations with the specified identifier. All date &amp; times are in UTC.
  # @param id Resource id.
  # @param [Hash] opts the optional parameters
  # @return [Reservation]
  describe 'reservations_reservation_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
