name: 'Lint SDK'
description: 'Lint SDK from a given directory'
inputs:
  module-name: 
    description: 'Name of the module to lint.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
    - uses: ./.github/workflows/composite/setup-ruby
    - name: Install rubocop (1.11)
      shell: bash
      run: sudo gem install rubocop --version 1.11
    - name: Lint module
      shell: bash
      run: cd ${{ inputs.module-name }} && rubocop --fail-level=error