name: 'Generate SDK'
description: 'Generate SDK for a given API'
inputs:
  spec-link: 
    description: 'Link to the spec file.'
    required: true
  module-name:
    description: 'Name of the ruby module.'
    required: true
  gem-name:
    description: 'Name of the ruby gem.'
runs:
  using: "composite"
  steps:
    - name: Logging head_ref and ref_name
      shell: bash
      run: |
        echo "head_ref = ${{github.head_ref}}"
        echo "ref_name = ${{github.ref_name}}"
    - name: Install node
      uses: actions/setup-node@v2
    - name: Install openapi-generator-cli
      shell: bash
      run: npm install -g @openapitools/openapi-generator-cli
    - name: Generate SDK
      shell: bash
      run: openapi-generator-cli generate -i ${{ inputs.spec-link }} -c openapi-generator-config.yaml -o ${{ inputs.module-name }} --additional-properties moduleName=${{ inputs.module-name }} --additional-properties gemName=${{ inputs.gem-name }}
    - name: Download spec files
      shell: bash
      run: wget ${{ inputs.spec-link }} -O ./${{ inputs.module-name }}/${{ inputs.module-name }}.spec.yaml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.module-name }}
        path: ${{ inputs.module-name }}
