name: (abstract) - Publish

on:
  workflow_call:
    inputs:
      dry_run:
        required: false
        type: boolean
      gem_to_publish:
        required: true
        type: string
    secrets:
      RUBYGEMS_API_KEY:
        required: true

env:
  GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

jobs:  
  publish-ruby-gems:
    name: Publish ${{ inputs.gem_to_publish }} to RubyGems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - if: ${{ !inputs.dry_run }}
        run: |
          echo Entering ${{ inputs.gem_to_publish }}...
          cd ./${{ inputs.gem_to_publish }}

          echo Building...
          gem build *.gemspec

          echo Publishing...
          gem push *.gem
