name: (abstract) - Test

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      test-file:
        required: true
        type: string

jobs:
  test:
    name: Test ${{ inputs.module-name }} ruby v ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    needs:
      - lint
    services:
      mockserver:
        image: mockserver/mockserver:5.15.0
        ports:
          - 1080:1080
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ '2.7', '3.1' ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/test-sdk
        with:
          test-file: ${{ inputs.test-file }}
          test-report-dir: tests
          ruby-version: ${{ matrix.ruby-version }}