name: validate-all

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:  
  # Build stage
  build-and-test-bmcapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: BmcApi
      test-file: tc_bmc_api.rb
  build-and-test-rancherapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: RancherApi
      test-file: tc_rancher_api.rb
  build-and-test-networkapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: NetworkApi
      test-file: tc_network_api.rb
  build-and-test-ipapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: IpApi
      test-file: tc_ip_api.rb
  build-and-test-auditapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: AuditApi
      test-file: tc_audit_api.rb
  build-and-test-tagapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: TagApi
      test-file: tc_tag_api.rb
  build-and-test-networkstorageapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: NetworkStorageApi
      test-file: tc_networkstorage_api.rb
  build-and-test-locationapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: LocationApi
      test-file: tc_location_api.rb
  build-and-test-paymentsapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: PaymentsApi
      test-file: tc_payments_api.rb
  build-and-test-invoicingapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: InvoicingApi
      test-file: tc_invoicing_api.rb
  build-and-test-billingapi:
    uses: ./.github/workflows/_common.yml
    with:
      module-name: BillingApi
      test-file: tc_billing_api.rb

  run-generic-tests:
    uses: ./.github/workflows/_test.yml
    with:
      module-name: "none (generic tests)"
      test-file: tc_misc_test.rb

  publish-test-results:
    name: Publish Test Results
    needs:
      - build-and-test-bmcapi
      - build-and-test-rancherapi
      - build-and-test-networkapi
      - build-and-test-ipapi
      - build-and-test-auditapi
      - build-and-test-tagapi
      - build-and-test-networkstorageapi
      - build-and-test-locationapi
      - build-and-test-paymentsapi
      - build-and-test-invoicingapi
      - build-and-test-billingapi
      - run-generic-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: test-reports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test-reports/**/*.xml
          check_name: "Test Results"